### ISSUE TITLE
(iOS) artoolkitX Camera Calibration Utility fails to build:  C-linkage specified, but returns user-defined type 'cv::Size'

### ISSUE THREAD

**Issue by PierreFritsch** [artoolkitx/artoolkitx-calibration#4]
The artoolkitx calibration app for iOS doesn't compile in the current version of Xcode (9.3) on the current version of macOS (10.13.3).

After specifying a Team in the Signing section of the "artoolkitX Camera Calibration Utility" target in Xcode, running `./build.sh ios` fails to build and reports the following error:

    In file included from /path/to/artoolkitx-calibration/prefsNull.cpp:41:
    ../prefs.hpp:61:10: error: 'getPreferencesCalibrationPatternSize' has C-linkage specified, but returns user-defined type
          'cv::Size' (aka 'Size_<int>') which is incompatible with C [-Werror,-Wreturn-type-c-linkage]
    cv::Size getPreferencesCalibrationPatternSize(void *preferences);
             ^

**Comment by PierreFritsch** [comment]
Thanks for your support @philip-lamb!
